project:
  type: website  
  resources:
    - ads.txt 

execute: 
  freeze: true

website:
  title: "Josiah Parry"
  google-analytics: "G-8NVVBLZBVF"
  sidebar:
    style: "docked"
    contents:
      # - href: index.qmd
      #   text: home 
      - text: "*want my help?*"
        href: services.qmd
      - about.qmd
      - href: posts/index.qmd
        text: "posts"
      - href: projects.qmd
      - section: socials
        contents:
        - icon: github
          href: https://github.com/josiahparry
          text: "GitHub"
        - icon: "linkedin"
          href: https://linkedin.com/in/josiahparry
          text: "LinkedIn"
        - icon: youtube
          text: YouTube
          href: https://www.youtube.com/@josiahparry
        - href: index.xml
          text: RSS
          icon: rss-fill
  twitter-card: true
  site-url: "https://josiahparry.com"

highlight-style: pygments
 
format:
  html:
    include-in-header:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9842567530621468" crossorigin="anonymous"></script>
    twitter-card:
      creator: "@josiahparry"
      #image: ""
      card-style: summary_large_image
    comments:
      utterances:
        repo: josiahparry/quarto-site
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 1em
    theme: 
      - lux
      - theming.scss
    css: styles.css
    mainfont: "Open Sans"






