project:
  type: site

website:
  title: "Josiah Parry"
  navbar:
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - href: posts/index.qmd
        text: "posts"
      - href: projects.qmd

format:
  html:
    theme: theming.scss
    css: styles.css
    toc: true
    mainfont: "Noto Serif"



